-- MySQL Script generated by MySQL Workbench
-- Fri Nov 16 17:57:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdRedes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdRedes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdRedes` DEFAULT CHARACTER SET utf8 ;
USE `bdRedes` ;

-- -----------------------------------------------------
-- Table `bdRedes`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdRedes`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bdRedes`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`, `nombre`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
usuario